### PR TITLE
Make html lighter a bit by uninlining css

### PR DESCRIPTION
**Pull request by aerfio**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by aerfio** [comment]
after playing for a while with it I've come to conclusion that uninlining css doesn't give us that much, as everything is cached (304 for main html file etc). Furthermore getting it to work with our wonderful styled-components+css setup is kinda not worth the hassle I think

And the sole idea of uninlining the styles should be discussed, because I'm not sure it's a good approach (again, cache, but it would need to be validated)

closing it for now

**Comment by aerfio** [comment]
Correction - it would probably be beneficial for new users, as we have swagger styles inlined in initial html....

**Comment by valentinvieriu** [comment]
@aerfio is this closing https://github.com/kyma-project/website/issues/574
Is it the same topic? Because if that's it, then we should reopen this.

**Comment by aerfio** [comment]
@valentinvieriu whooops, didn't mean to do it, sorry

**Pull request closed without merging**
