### PR TITLE
Request to add Pyxis into the 'Used by' Kyma page

### PR DESCRIPTION
**Pull request by gpolito**
Request to add Pyxis into the 'Used by' Kyma page

Changes proposed in this pull request:

- Pyxis logo
- adopters.xml updated with company description

**Related issue(s)**

### CODE REVIEW

**Comment by NHingerl** [comment]
Dear @gpolito, thank you for contributing! (and a happy new year!) 
Could you add some more details about the background of this change? Thanks a lot :)

**Comment by gpolito** [comment]
Hi @NHingerl, happy new year for you too!
The propose of this PR is to add our company (Pyxis, https://www.pyxis.cx/) as part of the _Used By_ list in the Kyma home page. I basically followed the steps listed here: https://github.com/kyma-project/website/blob/main/docs/add-user.md

**Review by NHingerl — APPROVED** [review]
Glad to have you on board, and congrats to the hack2build medal! 🎉

**Comment by gpolito** [comment]
thank you @NHingerl! 😄

**Pull request merged**
