### PR TITLE
Adapt documentation-component to single blog post page

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:
- Adapt documentation-component to single blog post page.
- improve main blog posts page with new styling - in progress.
- add info about estimated reading time on single blog post.
- start using `tooltip-tippy` instead of our tooltip.

**Related issue(s)**
Part of https://github.com/kyma-project/website/issues/142
https://github.com/kyma-project/website/issues/561

### CODE REVIEW

**Comment by valentinvieriu** [comment]
@magicmatatjahu 

Can we have a discussion about this before we approve the pull request? 
I think we loose a lot of horizontal real estate with this menu.

Also the code section is broken sometimes see [after-clean-up](https://deploy-preview-559--kyma-project.netlify.app/blog/2020/1/9/release-notes-19#rafter-clean-up)

**Comment by magicmatatjahu** [comment]
@valentinvieriu Yeah, sure! I only used this same component like in docs view, and only adapted content to right nav, so probably this same navigation may not looks good (and works) in blog post view.

About note panel: this is bug on css side (probably problem with positioning content on panel), so I will fix it.

Btw, welcome in Kyma team! :)

**Comment by valentinvieriu** [comment]
There is also a strange behavior in mobile view, looks like a share bar is all over the content.
It does affect negative the lighthouse score too. Lighthouse ( Performance index ) dropped 10 points on the new page. This could affect in a negative way SEO and page loading time too.
As those are the most relevant pages for SEO, we need to have  close eye on those metrics.

**Comment by magicmatatjahu** [comment]
I know about mobile and tablet devices. I wrote on PR's description about adopted styling only on desktop (at the moment of course). This PR is in draft, so I add `Work in progress` label :) I also wonder if showing right and left navigation after scrolling is good for UX. Wouldn't it be better to display immediately? I just copied this solution from some medium-based blogs.

I checked myself Lighthouse and yes, you have right. SEO dropped by around 10% and performances by around 40. I will try some layout configurations, with, without right nav, left nav with sharing buttons and see what exactly causes a decrease in performance. Thanks very much for info! 

The blog post view was not improved from the very beginning of Kyma's life, due to other topics related to my team in Kyma like new serverless, rafter or console, so we preferred to focus on the docs view.

Probably due to the fact that currently blog posts do not have extensive functionalities, their performances are really high, and we must focus on that topic.

**Comment by valentinvieriu** [comment]
@magicmatatjahu is the ShareBar something new to this pull request? Do we want to introduce a share bar too? Most content websites are focusing on clean content right now, and try to no distract the user from reading. 

If we want to give it a try, we need to track this and see if this feature is really used. Also Would be great to do the same for the navigation on the right.

Can we implement  [Event Tracking](https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide) on those elements, and see if our readers will use those new features?

Based on some readings around the web social buttons might not actually work:

- [why social sharing might not work](https://www.dannybrown.me/2016/10/20/why-social-sharing-buttons-might-not-be-needed-on-your-blog/)

- [Might be clever ways of using social sharing](https://www.seattlewebdesign.com/blog/seattle-web-design-online-marketing-blog/post/do-people-really-use-social-sharing-buttons)

**Comment by valentinvieriu** [comment]
Usability concerns: 

- If we make the whole blog section clickable, how are we going to solve teh tag clicking issue #275 ?
- It seems that on iPad, after you scrolled down, the back button takes you back to the previous anchor point ( this might be a bug - i'll report it )

**Comment by ketaki-r** [comment]
Hello all, I am a UX Designer working at SAP CX Labs Munich. I had a look at the blogpost page and I was wondering about the social button bar. To be honest I myself have never used the social button bar. But personally I think it is a nice option for the user to share the blog especially on platforms like LinkedIn. It is also good for SAP branding if users are sharing the blogs. One good point that you mentioned is that we can monitor the user behavior and somehow test if these buttons are being used. Also what I realised was that the social button bar is a bit too big and kind of distracting when i read the blog. I get why it is placed on the left- I guess for customer engagement so that the user is reminded to share it (also is easily visible). But I would prefer it on the bottom, when the user can see it after reading the blogpost. Hope this makes sense. Thank you!

**Comment by michal-hudy** [comment]
Regarding the new styles and behavior of the blog page (list of posts). Personally I think the old one looks better and is more intuitive. With the proposed solution, you are not able to click some links in the overview or tags as @valentinvieriu mentioned. Also, on mobile devices, you can click the blog post accidentally while scrolling. One thing on mobile devices, the new look consumes more space, the old one was more compact, so it was easier to read.

Next thing, on higher resolution, the page looks empty (loots of empty space on sides)

**Comment by valentinvieriu** [comment]
I'm missing the Read More button. I find it quite difficult to navigate from Blog Listing Page to Blog Detail page

Does then this pull add/change anything else then? Maybe we can rename and modify some of the description bulletpoints

image

**Pull request closed without merging**
