### PR TITLE
Add FAIR as new user

### PR DESCRIPTION
**Pull request by FAIRConsultingGroup**
**Description**

Changes proposed in this pull request:

- Add FAIR as new user

### CODE REVIEW

**Comment by derberg** [comment]
Thanks a lot for the contribution!

In order to process this pull request please adjust the “content” as it is too long. As you can see in the preview https://deploy-preview-507--kyma-project.netlify.com/ full content will not be visible. I suggest to remove reference to SAP Cloud Platform Extension Factory as Kyma website is purely for Kyma only.

Let us know if you need some help here. You can contact us directly on #kyma-project-io channel on our Slack http://slack.kyma-project.io/

**Comment by FAIRConsultingGroup** [comment]
Hi!

Thank you for your message! I've changed the text and committed the change.

Thanks in advance!

Felix

**Comment by derberg** [comment]
You are on the landing page https://twitter.com/kymaproject/status/1207613148683030530
If you want, you can also write a blog post on our kyma blog about your use case, like Netconomy just did https://kyma-project.io/blog/2019/12/20/netconomy-use-case

**Comment by FAIRConsultingGroup** [comment]
Thank you!

We have written a blog on kyma, it will be released soon. Once it is, I'll
get in touch with you ;)

**Pull request merged**
