### PR TITLE
Remove sticky left navigation

### PR DESCRIPTION
**Pull request by tgorgol**
**Description**

Changes proposed in this pull request:

- Remove sticky left navigation

**Related issue(s)**
https://github.com/kyma-project/website/issues/745

### CODE REVIEW

**Comment by tgorgol** [comment]
This PR should be merged after the new navigation tree PR.

**Comment by pPrecel** [comment]
> This PR should be merged after the new navigation tree PR.

IMO LGTM

**Comment by m00g3n** [comment]
LGTM

**Comment by tgorgol** [comment]
Closing this PR as it was cherry picked in https://github.com/kyma-project/website/pull/733

**Pull request closed without merging**
